### ISSUE TITLE
建议同时支持收款码和赞赏码

### ISSUE THREAD

**Issue by ylr9527** [lyy0709/vmq-itchat#4]
建议配置那里可以同时填收款码和赞赏码，就像至尊码支付微信监控那样，用户下单后，用收款码或者赞赏码支付都可以回调成功

**Comment by lyy0709** [comment]
可以但是麻烦，那个配置不好同时写，后面我会想个办法写上这个

**Comment by ylr9527** [comment]
> 可以但是麻烦，那个配置不好同时写，后面我会想个办法写上这个

感谢
