### ISSUE TITLE
监控心跳正常 检测不到通知

### ISSUE THREAD

**Issue by lonelyang** [lyy0709/vmq-itchat#7]
下载的是第18此提交的代码 如果mode设置为mode=zfhd而不是all会不断重启

**Comment by lyy0709** [comment]
关于models选择zfhd无法启动需要给我截图一下日志，关于无法监测收款信息，itchat回调不是直接监控账单和余额，是监控微信收款助手的收款卡片，需要能正常收到收款卡片才能监控正常,最后请重新拉更新

**Comment by lonelyang** [comment]
![image](https://github.com/user-attachments/assets/2cef2163-2b18-45d0-acb0-3c08dbe928fd)
la拉取了最新的更新 似乎情况变糟了

**Comment by lonelyang** [comment]
下图为mode=all 正常启动心跳检查 我已确认可以账号收到微信收款助手发送的收款卡片 但监控端依旧检测不到收款信息
![image](https://github.com/user-attachments/assets/c5a8958b-bb51-4a0d-93d4-3bba52349cf9)

**Comment by lonelyang** [comment]
下图为最新提交models选择zfhd时的日志 运行到这里会自动关闭容器
![image](https://github.com/user-attachments/assets/bd866049-9c0c-474d-a6be-0b406c35fb92)

**Comment by lyy0709** [comment]
不对啊，你没有完全拉更新吧，我测试是正常的

**Comment by lonelyang** [comment]
![image](https://github.com/user-attachments/assets/9380f93f-ae7c-4f78-b43b-f6815744e6a9)
最后不用容器了 测试功能基本正常 就是打印的消息有点小错误
